# Generated by Django 3.2 on 2022-06-07 18:54

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_remove_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=image.models.upload_loacation),
        ),
    ]
