# Generated by Django 3.2 on 2022-12-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=-1),
        ),
    ]
